# Generated by Django 5.0.3 on 2024-03-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gunplas',
            new_name='Gunpla',
        ),
    ]
